name: scale-dit
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.9.0
      - torchvision==0.24.0
      - lightning==2.5.5
      - accelerate==1.10.1
      - diffusers==0.31.0
      - transformers==4.57.1
      - peft==0.17.1
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - datasets==4.2.0
      - pyyaml==6.0.3
      - pillow==11.3.0
      - opencv-python==4.12.0.88
      - psutil==7.1.0
      - prodigyopt==1.1.2
      - wandb==0.22.2
